// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");

var getInputJSLine = (
      function() {
        const readlineSync = require('readline-sync');
        const rl = readlineSync;
        var ans = rl.question('Test readline-sync by typing something and hitting enter ');
        return ans;
    });

function test(param) {
  var input = Curry._1(getInputJSLine, /* () */0);
  console.log(input);
  return /* () */0;
}

test(/* () */0);

exports.getInputJSLine = getInputJSLine;
exports.test = test;
/* getInputJSLine Not a pure module */
